/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcRouteImport } from './routes/ac'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as CheckRouteImport } from './routes/check'
import { Route as HashRouteImport } from './routes/hash'
import { Route as MooaRouteImport } from './routes/mooa'
import { Route as OutcomesRouteImport } from './routes/outcomes'
import { Route as RegistrarsRouteImport } from './routes/registrars'
import { Route as StackRouteImport } from './routes/stack'
import { Route as StoryRouteImport } from './routes/story'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcRoute = AcRouteImport.update({
  id: '/ac',
  path: '/ac',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const HashRoute = HashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const MooaRoute = MooaRouteImport.update({
  id: '/mooa',
  path: '/mooa',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesRoute = OutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarsRoute = RegistrarsRouteImport.update({
  id: '/registrars',
  path: '/registrars',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ac': typeof AcRoute
  '/badges': typeof BadgesRoute
  '/check': typeof CheckRoute
  '/hash': typeof HashRoute
  '/mooa': typeof MooaRoute
  '/outcomes': typeof OutcomesRoute
  '/registrars': typeof RegistrarsRoute
  '/stack': typeof StackRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ac': typeof AcRoute
  '/badges': typeof BadgesRoute
  '/check': typeof CheckRoute
  '/hash': typeof HashRoute
  '/mooa': typeof MooaRoute
  '/outcomes': typeof OutcomesRoute
  '/registrars': typeof RegistrarsRoute
  '/stack': typeof StackRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ac': typeof AcRoute
  '/badges': typeof BadgesRoute
  '/check': typeof CheckRoute
  '/hash': typeof HashRoute
  '/mooa': typeof MooaRoute
  '/outcomes': typeof OutcomesRoute
  '/registrars': typeof RegistrarsRoute
  '/stack': typeof StackRoute
  '/story': typeof StoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ac'
    | '/badges'
    | '/check'
    | '/hash'
    | '/mooa'
    | '/outcomes'
    | '/registrars'
    | '/stack'
    | '/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ac'
    | '/badges'
    | '/check'
    | '/hash'
    | '/mooa'
    | '/outcomes'
    | '/registrars'
    | '/stack'
    | '/story'
  id:
    | '__root__'
    | '/'
    | '/ac'
    | '/badges'
    | '/check'
    | '/hash'
    | '/mooa'
    | '/outcomes'
    | '/registrars'
    | '/stack'
    | '/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcRoute: typeof AcRoute
  BadgesRoute: typeof BadgesRoute
  CheckRoute: typeof CheckRoute
  HashRoute: typeof HashRoute
  MooaRoute: typeof MooaRoute
  OutcomesRoute: typeof OutcomesRoute
  RegistrarsRoute: typeof RegistrarsRoute
  StackRoute: typeof StackRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac': {
      id: '/ac'
      path: '/ac'
      fullPath: '/ac'
      preLoaderRoute: typeof AcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash': {
      id: '/hash'
      path: '/hash'
      fullPath: '/hash'
      preLoaderRoute: typeof HashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mooa': {
      id: '/mooa'
      path: '/mooa'
      fullPath: '/mooa'
      preLoaderRoute: typeof MooaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes': {
      id: '/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof OutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrars': {
      id: '/registrars'
      path: '/registrars'
      fullPath: '/registrars'
      preLoaderRoute: typeof RegistrarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcRoute: AcRoute,
  BadgesRoute: BadgesRoute,
  CheckRoute: CheckRoute,
  HashRoute: HashRoute,
  MooaRoute: MooaRoute,
  OutcomesRoute: OutcomesRoute,
  RegistrarsRoute: RegistrarsRoute,
  StackRoute: StackRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
